### ISSUE TITLE
Stale Branch 77-SortingFiltering

### ISSUE THREAD

**Issue by RainbowPangolin** [cse110-fa21-group2/cse110-fa21-group2#105]
[This branch seems to be stale](77-SortingFiltering);

Is this still being worked on, or can we close it?

**Comment by fjontran** [comment]
> [This branch seems to be stale](77-SortingFiltering);
> 
> Is this still being worked on, or can we close it?

I was supposed to work on the CSS for the sorting but not the actual sorting itself?

**Comment by treeebooor** [comment]
I was gonna do the filtering/sorting API functions on this branch

**Comment by RainbowPangolin** [comment]
Gotcha. Closing Issue.
