### ISSUE TITLE
Update wiki with Notes on Bootstrap

### ISSUE THREAD

**Issue by RainbowPangolin** [cse110-fa21-group2/cse110-fa21-group2#20]
Team needs more information on Bootstrap. Please update the wiki with relevant links.

**Comment by RainbowPangolin** [comment]
I created the Main Dev Doc page (https://github.com/cse110-fa21-group2/cse110-fa21-group2/wiki/Main-Developer-Doc). Please put the relevant info here.

**Comment by RainbowPangolin** [comment]
Bump. We might continue to use Bootstrap. We can decide on that in the  Mob Programming Session

**Comment by hzhfred** [comment]
Added to our WIki !
