### ISSUE TITLE
Add duplicate 'apply to search' button to top of sort/filter box

### ISSUE THREAD

**Issue by RainbowPangolin** [cse110-fa21-group2/cse110-fa21-group2#211]
By default, the sort and filter box is uncollapsed, meaning that if I make any sort/filter changes, I have to scroll all the way down to click the Apply button. There should be a duplicate of this button at the top to make it more convenient if I'm, say, just using the sort-by functions and not all the other filters. 

![image](https://user-images.githubusercontent.com/43018668/144765021-f2add4e7-91fa-4446-bedc-34d56337199b.png)

**Comment by fjontran** [comment]
I've worked on this issue!

**Comment by AlexNguyenJJ** [comment]
> I've worked on this issue!

Wait I didn't see you assign this to yourself so I didn't know it was worked on! ;-;

**Comment by fjontran** [comment]
No worriesss
