### ISSUE TITLE
Improve sort/filter 'apply' button visibility

### ISSUE THREAD

**Issue by RainbowPangolin** [cse110-fa21-group2/cse110-fa21-group2#213]
The default button doesn't stand out. It might help to make it a different color, such as yellow. and bold the text. 

![image](https://user-images.githubusercontent.com/43018668/144765074-862c504f-2cc5-4ba4-b37f-02d95a17cfc6.png)

**Comment by fjontran** [comment]
Is this better? 
![image](https://user-images.githubusercontent.com/60120797/145504299-981e74a3-9567-410b-8b64-b434cf78189a.png)
It also darkens when you are hovering over it
