### ISSUE TITLE
lint your own code

### ISSUE THREAD

**Issue by farisashai** [cse110-fa21-group2/cse110-fa21-group2#55]
**Describe the bug**
we dont have the linter ci action set up yet but all of the js code right now is failing for style in a million diff places

**To Reproduce**
1. Run `npm install`
2. Run `npm run lintjs`
3. Make sure there are no errors in your JS files

**Expected behavior**
no errors

**Screenshots**
<img width="802" alt="Screen Shot 2021-11-16 at 5 29 52 PM" src="https://user-images.githubusercontent.com/33165426/142092623-08350c86-1729-47a1-b786-7b18b6293b22.png">

**Comment by RainbowPangolin** [comment]
Everyone should be on the same page as far as style goes now. We still need to check the linter rules so that it doesn't deny anything stupid.
