### ISSUE TITLE
BootStrap NavBar Hamburger 

### ISSUE THREAD

**Issue by RainbowPangolin** [cse110-fa21-group2/cse110-fa21-group2#61]
# Describe the Bug
BootStrap is causing the Hamburger Icon in the top right of the NavBar to disappear on mobile devices/small windows.

See [this link](https://getbootstrap.com/docs/5.1/components/navbar/) to help fix. 

We want the icon to appear on mobile. 

# Story points

~1

**Comment by BritneyVi** [comment]
Error - not a bug 

Being re-issued as a feature implementation
