### ISSUE TITLE
[IMPLEMENT] main.js - Write event handler for navbar search button to fetch API results for query and populate search results cards

### ISSUE THREAD

**Issue by BritneyVi** [cse110-fa21-group2/cse110-fa21-group2#70]
# Feature Name

main.js - Write event handler for navbar search button to fetch API results for query and populate search results cards

# User Story

Our users would like to be able to search on our app.

Details: 
- add even handler to search button to fetch recipes for query 
- add recipes to localStorage 
- populate search result cards 
- navigate to search results page

**Comment by hanran-y** [comment]
update: old branch deleted.
I will delete the old 70- branch once I finished the conflicts caused by the update.

**Comment by hanran-y** [comment]
The API is currently down, waiting API provider responds.

event handler for navbar search button to fetch API results for query and populate search results cards Is now working. 
searchResultShowMore button is working, but lack of testing due to API down.
