### ISSUE TITLE
[IMPLEMENT] Recipe Card - Web Component

### ISSUE THREAD

**Issue by BritneyVi** [cse110-fa21-group2/cse110-fa21-group2#72]
# Feature Name

Recipe Card - Web Component

# User Story

Our users would like a working Recipe Card where they can easily see the name of the recipe and an image of the finished product.

Details: 
Creating the recipe card web component. 
- Has to have the ability to populate data fields using JSON object from localStorage. 
- Save recipe button
- Navigate to expanded info page on click
- Switch icon when saved

**Comment by RainbowPangolin** [comment]
Largely completed, but recipe cards need to populate with real data ASAP.
