### ISSUE TITLE
[IMPLEMENT] Recipe Card - CSS

### ISSUE THREAD

**Issue by BritneyVi** [cse110-fa21-group2/cse110-fa21-group2#73]
# Feature Name

Recipe Card - CSS

# User Story

Our users would like the recipe cards to be clean, intuitive, and visually appealing

Details: 
- Finalize card layout and match Figma

**Comment by farisashai** [comment]
as a follow up to this ticket, we need to 
1. update RecipeCard.js web component html structure to match identically and copy the new CSS in to match
2. make the set data function in recipecard.js correctly populate the full card with info from the json object with recipe data
