### ISSUE TITLE
[IMPLEMENT] Saved Recipes Navbar Dropdown - Display different lists as easily accessible options

### ISSUE THREAD

**Issue by BritneyVi** [cse110-fa21-group2/cse110-fa21-group2#80]
# Feature Name

Saved Recipes Navbar Dropdown - Display different lists as easily accessible options

# User Story

Users of our app would like to be able to more easily navigate to their custom lists from other pages

Details: 
- allow users to edit anything in the recipe’s schema and update their local storage with the changes.

**Comment by RainbowPangolin** [comment]
Deprecated
