### ISSUE TITLE
Netlify not deploying 

### ISSUE THREAD

**Issue by RainbowPangolin** [cse110-fa21-group2/cse110-fa21-group2#82]
# Describe the Bug
Netlify bot's deploy-preview returns a 'page not found' page. 

# Additional Notes
If this is due to our own improper usage of Netlify, please document the correct steps. See #45.

**Comment by farisashai** [comment]
@RainbowPangolin my bad it was just looking in the repo's base folder for an index.html file rather than source/ by default. i updated the build settings.
[Main Branch Deploy](https://recipe-manager-team-h20.netlify.app/)
