### ISSUE TITLE
Check localStorage before fetching

### ISSUE THREAD

**Issue by treeebooor** [cse110-fa21-group2/cse110-fa21-group2#88]
# Is your feature request related to a problem? Please describe.
Unnecessary fetching when the recipes are already in Local Storage.
# Describe the solution you'd like 
Before fetching from API, check if the recipes are already in Local Storage.
# Describe alternatives you've considered

# Additional context

# Story Points
5pts

**Comment by RainbowPangolin** [comment]
If the Spoonacular database is updated at all, then wouldn't any previous fetches 'burn in' and thus not be updated if you search again? e.g. If I searched for cookie recipes matching X tags a month ago, didn't touch my local storage, and want to search for new ones, wouldn't that be impossible?

**Comment by treeebooor** [comment]
This check is to make sure we are not fetching the exact same recipe id if its already in local storage. The API should have unique ids for each recipe so I would think that id will be changed if the database is updated. I'm trying to prevent repeated API calls to the exact same recipe because the calls are kinda expensive.

**Comment by RainbowPangolin** [comment]
Ah, okay so if you can check the id of the recipe before it's fetched and grab from local storage instead, that would actually be good.
